### ISSUE TITLE
Add Basmala u+FDFD character

### ISSUE THREAD

**Issue by fsiefken** [alif-type/reem-kufi#11]
@khaledhosny The Basmala u+FDFD isn't in the font.
http://www.decodeunicode.org/u+FDFD
It's part of 'Arabic Presentation Forms A' which has common liturgical phrases.
https://en.wikipedia.org/wiki/Arabic_script_in_Unicode
Perhaps you can add it or have the character sequence as an example in the README, as I am not sure how it is written.
For those not knowing what it represents, it's the used in the recitation of the Quran, the arabic phrase means "In the name of God, the Most Gracious, the Most Merciful"
https://en.wikipedia.org/wiki/Basmala

**Comment by khaledhosny** [comment]
What do you need U+FDFD for? It is mostly a legacy compatibility character and you shouldn’t use it unless you have a very good reason to do so.

The basmala is just a regular Arabic phrase and you can right it like any other Arabic text; “بسم الله الرحمن الرحيم”.
