### ISSUE TITLE
Add vowel marks

### ISSUE THREAD

**Issue by munzirtaha** [alif-type/reem-kufi#13]
جربت استخدام الخط في أسماء سور القرآن بحسب الكود الذي وضعته أخي خالد في ملف
build_html.py
لكن واضح أن بعض أسماء السور لم تعرض بصورة صحيحة بسبب غياب بعض المحارف مثل 
uni06E1, uni0670, ...

**Comment by khaledhosny** [comment]
This is fixed now.

**Comment by munzirtaha** [comment]
For me it's not fixed yet. Attached is how Reem Kufi renders Sura names in Chromium and Scribus

![alimran](https://user-images.githubusercontent.com/2936425/32394535-803642a0-c0ee-11e7-8258-ba39ff396a97.png)
![sajdah](https://user-images.githubusercontent.com/2936425/32394536-805a4524-c0ee-11e7-89bd-c2ff7e819490.png)
![scribus](https://user-images.githubusercontent.com/2936425/32394537-808be890-c0ee-11e7-97e5-f4fd7f31f4fa.png)

**Comment by khaledhosny** [comment]
Oh, I forgot that I still need more marks and to fix positioning below base ones.

**Comment by khaledhosny** [comment]
Should be fixed for real now.

**Comment by davelab6** [comment]
Sweet!!

**Comment by munzirtaha** [comment]
Strange! I am still facing the exact same problem.
> otfinfo --info .local/share/fonts/ALIF/ReemKufi-Regular.otf 
Version:             Version 0.005
Unique ID:           0.005;ALIF;ReemKufi-Regular

What other info do you ask for? Can you please leave it open and give me a grace period to test and confirm?

**Comment by khaledhosny** [comment]
You might want to run `fc-cache -rf` for some applications to recognize the new glyphs. Note also that I didn’t support the Quran variant of the sukun on the font, I [updated my sura names to not use it](https://github.com/khaledhosny/quran-data/commit/68e3a77bb5aab6bddebf72612dd2f9a8f4fac550) instead.

**Comment by khaledhosny** [comment]
Here is a screenshot:
![screenshot-2017-11-4 screenshot](https://user-images.githubusercontent.com/93914/32409632-0f71a2a6-c1b8-11e7-8d2b-fd93be02bd5f.png)

**Comment by munzirtaha** [comment]
But the Quran variant of the sukun is what is used in Mushaf Al-Madina and Mushaf Al-Amiri and I believe it's better to, at least, support those marks used in Masahif at minimum if not all the vowel marks

**Comment by khaledhosny** [comment]
I might do eventually, but this is a rather old Kufi design and vowel marks don’t really fit in, so I’d rather support as few as possible.

**Comment by khaledhosny** [comment]
بالمناسبة، أسماء السور في المصحف الأميري تستخدم السكون العادي، استخدامي لعلامة الجزم كان فذلكة مني.

**Comment by munzirtaha** [comment]
لا، ليست فذلكة منك، المصحف الأميري يستخدم كلا العلامتين في أسماء السور ولعل هذا سهو منهم غير مقصود أو تساهل منهم والأمر واسع في أسماء السور، مثلا

![screenshot_20171105_053726](https://user-images.githubusercontent.com/2936425/32411645-397c5db8-c1f2-11e7-82fe-405045a0e470.png)

ولا معنى لكلمة الجزم هنا فالقضية ليست حركة إعراب وإنما شكل فقط ولا فرق بين علامة السكون سواء استخدمت في نص الآية أو في اسم السورة فلا أرى داع للتفريق بينهما واتباع نسق واحد أولى والله أعلم

أما كون أن الخط الكوفي القديم لا يناسبه وضع الحركات فأنت أخبر مني بذلك وإن كنت لا أحسبه صحيحا لأني رأيته كثيرا في المخطوطات القديمة، مثلا

![qur an_folio_11th_century_kufic](https://user-images.githubusercontent.com/2936425/32411667-a1b7aa0e-c1f2-11e7-84a9-9ecdc62e16e0.jpeg)

والقرار أولا وأخيرا لكم فقد ترون أنكم حين طورتم هذا الخط لم يكن لغرض أسماء السور أو كتابة الآيات، لكنه خيار ربما رغب فيه البعض، وفقكم الله فقد أسهمتم بالكثير
