### ISSUE TITLE
Mac nametable records missing 

### ISSUE THREAD

**Issue by m4rc1e** [alif-type/reem-kufi#16]
In version 0.004 (version currently hosted on GF), there were Mac records in the nametable. These are missing in 0.6.

**Comment by khaledhosny** [comment]
The fonts are built by fontmake, so it includes whatever names fontmake generates. But does it matter? I think these names are required for old Mac applications like old versions of Word, but these applicatiobs don’t typically support OpenType Arabic fonts anyway.

**Comment by m4rc1e** [comment]
@khaledhosny thanks that's sounds logic!

This has already been flagged in https://github.com/googlei18n/ufo2ft/issues/58.
