### ISSUE TITLE
Cropped vowels

### ISSUE THREAD

**Issue by philipzae** [alif-type/reem-kufi#17]
Was trying out the new vowelled version of reem with some sample text and noticed that some were going to high when inside a table and were being cropped. This was with single line spacing

![reem kufi vowels](https://user-images.githubusercontent.com/4412114/34071539-05637c2c-e291-11e7-8107-419b309ba58b.png)

top row is how the vowels looked cropped when scrolling up and down in a document and bottom row is when alt+tabbing into LO from another app.

**Comment by khaledhosny** [comment]
This is a LibreOffice bug. I increased the clipping metrics in 3e84f25bb904e16cb8329c868ccf9b170d43dbce, but it makes no difference with LibreOffice so I suspect it is not using them and is instead using the line height for clipping.

**Comment by philipzae** [comment]
Happens in LO 5.2 as well, so not a harfbuzz regression, so guess the commit isnt really necessary. :D

**Comment by khaledhosny** [comment]
It does not fix the issue in LibreOffice, but it might fix similar clipping in other Windows applications.
