### ISSUE TITLE
Characters Have No Unicode Hex Values + Unity Issue

### ISSUE THREAD

**Issue by AlexisDrain** [alif-type/reem-kufi#18]
Basically, I'm trying to make "ReemKufi-Regular.otf" work in Unity on Windows.

I tried adding this font in two methods:
1- Using the default Unity UI + Arabic Support plugin.
2- Using TextMeshPro plugin.
In both cases, however, Reem Kufi doesn't work.

![sprite-0004](https://user-images.githubusercontent.com/32722574/38407908-4f30bc02-3949-11e8-808b-c2e06762cd4c.png)
(Reem Kufi compared to Cairo in Unity)

Here's what I think is the issue:  

I opened ReemKufi-Regular.otf in FontForge and in FontLab, but none of the main Arabic letters had any unicode hex values. I think these unicode hex values are needed for Unity to display the font.  

Notice the question marks in these two images:

![sprite-0002](https://user-images.githubusercontent.com/32722574/38407678-6e211554-3948-11e8-9dde-521c97632c71.png)
(FontForge)

![sprite-0003](https://user-images.githubusercontent.com/32722574/38407709-8ba9506e-3948-11e8-832a-27223c135f2b.png)
(FontLab)

**Comment by khaledhosny** [comment]
The way the font is built requires an OpenType layout engine, looks like Unity does not use one.
