### ISSUE TITLE
Font does not work in Word

### ISSUE THREAD

**Issue by hkmbs** [alif-type/reem-kufi#19]

**Comment by khaledhosny** [comment]
Please elaborate and attach a screenshot if possible. “Does not work” is to generic.

**Comment by hkmbs** [comment]
When I try to type in Reem Kufi in Word, the text is not be displayed in Reem Kufi but instead it uses Arial automatically.

**Comment by Samer-** [comment]
I am having the same issue with Word on Windows 10. Trying to set an Arabic phrase to Reem Kufi defaults to Arial. Strangely, Reem Kufi seems to work with English. 
There are no error messages.

![image](https://user-images.githubusercontent.com/8712761/204078656-17368980-1fed-4013-9594-f28b1596a382.png)

![image](https://user-images.githubusercontent.com/8712761/204078677-67af3e7f-9467-44e3-9952-ae5db65fa017.png)

![image](https://user-images.githubusercontent.com/8712761/204078683-4be68f96-63ee-4b5c-b0d8-d9ef22352386.png)

**Comment by khaledhosny** [comment]
Which version of the font are you installing and what is the file name of the font?

**Comment by Samer-** [comment]
The file name is ReemKufi.otf (downloaded from here: https://github.com/aliftype/reem-kufi/tree/main/fonts). I couldn't find a version number except in the screenshot. 

![image](https://user-images.githubusercontent.com/8712761/204089619-950cea7b-c96b-419d-b479-ceec5b037be4.png)

**Comment by khaledhosny** [comment]
Download the latest version from https://github.com/aliftype/reem-kufi/releases.

**Comment by Samer-** [comment]
Thank you so much, sorry to disturb you. The TTF works perfectly for me.
