### ISSUE TITLE
Three Arabic letters doesn't exist in the font design

### ISSUE THREAD

**Issue by Oxibug** [alif-type/reem-kufi#20]
Hi Pal,

The font design doesn't have very important three Arabic letters...

1. **ى** - (Ya) - Is same as { **ي** } BUT without dots at the bottom and this letter always come at the end of the word. - Example { **أقصى** }

2. **ئ** - Is same as { **ى** } BUT it has { Hamza } above - Example { **سيئ** }

3. **ة** - (Circled - Ta) Is same as { **ه** } BUT it has two dots above - Example { **شجرة** }

![Example Image](https://awscdn.oxibug.com/cdn/wp-content/uploads/2018/09/Font-ReemKufi.png)

Thanks for your great font.

**Comment by khaledhosny** [comment]
The font have all these characters, looks like a bug elsewhere.
