### ISSUE TITLE
Support Arabic Presentation Forms

### ISSUE THREAD

**Issue by ashrafkamel5** [alif-type/reem-kufi#23]
I have a problem trying to use your font Reem-Kufi, 
It's an Embedded project in C.
and I am converting the .ttf font file to .c file using [an online converter](https://lvgl.io/tools/fontconverter).
The problem is that I can't find the [Arabic Presentation Forms-B](https://unicode-table.com/en/blocks/arabic-presentation-forms-b/) Unicode ranges "0xFE70-0xFEFF" In the .ttf file.
This is the range responsible for the different writings of the Arabic letters.
so I am only able to write individual letters 
" أ ه ل ا"
not a whole word
"أهلا"
when checking the font.ttf at [fontdrop]( https://fontdrop.info/) website.
it shows the glyphs but with Unicode none. 

![image](https://user-images.githubusercontent.com/38524812/97122790-2108e700-1731-11eb-86cc-e8185b3e8d4d.png)

where the individual letters have a valid Unicode ranged 0x0600-0x06FF.

![image](https://user-images.githubusercontent.com/38524812/97122796-33832080-1731-11eb-872a-1fdacf55adde.png) 
 
The thing is that all of the online websites are able to recognize the font despite that.

![image](https://user-images.githubusercontent.com/38524812/97122828-51e91c00-1731-11eb-9add-b667544c397d.png)

all of the screenshots are from the FontDrop website mentioned earlier.
So how does this work?

**Comment by khaledhosny** [comment]
The font requires an OpenType layout engine, it can’t be used without one.

**Comment by ashrafkamel5** [comment]
Mmmmmm, 
can you just provide a .ttf version with the lost unicode ranges covered?
I am really keen on using this font in my project.
really loved it.
It is very beautiful. <3  
or can I do this by myself if you are busy at the moment?
could you show me how?

**Comment by khaledhosny** [comment]
It requires a quite bit of work and basically restructuring the whole font since it isn't just about missing presentation forms code points.

**Comment by ashrafkamel5** [comment]
😥😥😥😥😥😥😥😥😥
Thanks.

**Comment by ashrafkamel5** [comment]
Just keep an intention for such addition if you had the chance to add something new.
I will keep an eye on the project tho.

**Comment by khaledhosny** [comment]
This is unlikely to happen by me, sorry. Almost all my fonts require an OpenType layout engine, legacy systems depending on the legacy presentation forms is not something I intend to ever support, since they give the illusion of supporting Arabic while giving a far inferior experience compared to non-legacy systems that support OpenType.

**Comment by ashrafkamel5** [comment]
ok, thanks for the elaboration,
It is just the embedded systems field that is just kicking in the whole GUI era.
limited hardware resources and so.
Many thanks for your concern. ❤

**Comment by khaledhosny** [comment]
I understand the limitation, but I also don’t support compromising Arabic support in the name of limited resources, not in 2020 anyway. Such systems also don’t support many more languages and writing systems that can’t be hacked with things like presentation forms (e.g. many Indic and South Asian languages) and better invest in integrating a real layout engine like [HarfBuzz](https://harfbuzz.github.io/).

**Comment by ashrafkamel5** [comment]
Thanks god.
I did it using` FongForge`
here is the .woff file the .ttf has a problem I am too inexperience to understand 
[ReemKufi-Regular.zip](https://github.com/alif-type/reem-kufi/files/5444729/ReemKufi-Regular.zip)
