### ISSUE TITLE
U+061B and U+060C have a strange appearance in the bold master

### ISSUE THREAD

**Issue by ctrlcctrlv** [alif-type/reem-kufi#24]
Is it intentional? The self-intersecting outline leads me to doubt it.

![image](https://user-images.githubusercontent.com/838783/99889459-59a1c080-2c0a-11eb-8065-de4c4f9db2ab.png)

**Comment by khaledhosny** [comment]
Glyphs calls these outside open corners but glyphsLib/ufo2ft [do not support removing them](https://github.com/googlefonts/glyphsLib/issues/255). I usually ovoid them, or remove them manually when done but I missed this glyph (I actaully fixed it in my working tree, but it is part of an unfinished work that I didn’t push yet.
