### ISSUE TITLE
letter overlap

### ISSUE THREAD

**Issue by BilalBoulifa** [alif-type/reem-kufi#25]
just write الشيخ and take a look at how the letters overlap.

**Comment by BilalBoulifa** [comment]
why this ticket has been closed? if the issue has been solved or there is already a solution to the issue, leave a comment please, so others will know.

**Comment by khaledhosny** [comment]
It was fixed and the fix is linked in the action that closed the issue, which happens automatically when a commit message mentions it fixed an issue.
