### ISSUE TITLE
reem-kufi incorrect appearance in Chrome

### ISSUE THREAD

**Issue by drott** [alif-type/reem-kufi#26]
oliverwilliams345@gmail.com reports in https://bugs.chromium.org/p/chromium/issues/detail?id=1170733#c16: 

> I tried a COLRv1 typeface in Chrome 98 on Mac Big Sur with the flag enabled and it just appears as solid black. https://github.com/aliftype/reem-kufi/blob/colr-v1/ReemKufiInk-Regular.ttf
> I checked this font in Font Goggles software and it has a lovely gradient.

My take:
If it looks okay in an older version of FontGoogles before https://github.com/BlackFoundryCom/black-renderer/issues/35 was closed, then it may mean that the reem-kufi font is not produced with the latest spec changes.

It seems to work for me with Chrome built from tip of tree, COLRv1 enabled:

![kufi](https://user-images.githubusercontent.com/1021784/140736724-4361fd3c-5bf6-4449-9593-59628adf3bee.png)

I am not 100% sure what's the expected appearance but this looks like the font is built according to the latest spec and renders ok. 

It's still important to use the latest Chrome Canary with the flag enabled. Any older versions are not expected to work 100% robustly.

**Comment by khaledhosny** [comment]
The COLR table is built with the latest nanoemeji release and it should be up to the latest spec. Case in point, it didn't work in FontGoggles until it's latest release. My guess is that the reporter failed to restart Chrome after setting the flag, I myself fell for this when I tried COLR v1 fonts for the first time.

**Comment by drott** [comment]
As @khaledhosny didn't mention anything about the screenshot being unusual, closing this. oliverwilliams345@gmail.com, please comment if there are still obstacles to getting to the right rendering.

**Comment by khaledhosny** [comment]
Just to be clear, the above screenshot is the expected look of the font.
