### ISSUE TITLE
nanoemoji glyphmap.csv added additional column, breaks mkglyphmap.py

### ISSUE THREAD

**Issue by anthrotype** [alif-type/reem-kufi#29]
Heads up, in the latest nanoemoji we needed to modify the format of the glyphmap.csv file to accommodate for hybrid vector+bitmap color fonts (with both COLR, OT-SVG and CBDT tables), thus we added a column for the .PNG sources. The expected format is now 

svg_file, png_file, glyph_name, codepoints*

Either the first or the second filenames can be left empty depending on whether it's vector-only, bitmap-only or hybrid.

**Comment by khaledhosny** [comment]
Thanks for the heads up. I’ll keep this in mind when updating the dependencies.
