### ISSUE TITLE
Prepare Reem Kufi Color for Google Fonts

### ISSUE THREAD

**Issue by yanone** [alif-type/reem-kufi#31]
Hi Khaled,

the Ink TTF fonts in this repo don't render als COLRv1 at all, only b/w. 
Your build process is too unknown for me to be able to dig in, so I need to ask you to please investigate this and update the files as necessary.

Thank you

**Comment by khaledhosny** [comment]
Should be fixed now. The build process is indeed too brittle. I’m trying to migrate color glyphs to Glyphs color layers (which should hopefully simplify the setup), but I’m blocked because they can’t represent what I have already https://forum.glyphsapp.com/t/gradient-transform/22169
