### ISSUE TITLE
Missing Arabic full stop U+06D4

### ISSUE THREAD

**Issue by chrissimpkins** [alif-type/reem-kufi#35]
We are seeing tofu on the fonts.google.com Reem Kufi, Reem Kufi Ink, and Reem Kufi Fun type tester text previews that include the Arabic full stop (U+06D4) glyph.  

<img width="1018" alt="reemkufi" src="https://user-images.githubusercontent.com/4249591/187554183-e87c94ae-2504-48ba-8832-ed7ab3a0b47b.png">
<img width="1015" alt="reemkufifun" src="https://user-images.githubusercontent.com/4249591/187554193-06bfe449-8928-4d39-a7b2-852589d8e7d9.png">
<img width="1022" alt="reemkufiink" src="https://user-images.githubusercontent.com/4249591/187554208-8c0c5b84-6f96-4bd7-9314-f878ce75ccf6.png">

Is this glyph intentionally absent from the glyph set?  If not, is it possible to include support in a new release?

**Comment by chrissimpkins** [comment]
Repro text run:

کسی شخص کو محض حاکم کی مرضی پر گرفتار، نظربند، یا جلاوطن نہیں کیا جائے گا۔\nہر ایک شخص کو یکساں طور پر حق حاصل ہے کہ اس کے حقوق و فرائض کا تعین یا اس کے خلاف کسی عائد کردہ جرم کے بارے میں مقدمے کی سماعت آزاد اور غیر جانبدار عدالت کے کھلے اجلاس میں منصفانہ طریقے سے ہو۔\nکسی شخص کی نجی زندگی، خانگی زندگی، گھربار، یا خط و کتابت میں من مانے طریقے پر مداخلت نہ کی جائے گی اور نہ ہی اس کی عزت اور نیک نامی پر حملے کیے جائیں گے۔ ہر شخص کو حق حاصل ہے کہ قانون اسے حملے یا مداخلت سے محفوظ رکھے۔

**Comment by khaledhosny** [comment]
Let me know if you need me to cut a release as well.

**Comment by chrissimpkins** [comment]
Documenting here that U+06D4 is used in Urdu, not in Arabic / Persian based on a conversation with Khaled in another thread.
