### ISSUE TITLE
Reem Kufi Fun missing SVG table

### ISSUE THREAD

**Issue by yanone** [alif-type/reem-kufi#37]
Me again, sorry.

Please integrate `maximum_color` of the `nanoemoji` package into your build setup to expand the `COLR` table into an `SVG` table and provide us with a new binary.

Thank you.

**Comment by yanone** [comment]
Also, while you're at it, please update the name table to the "expected" values:

nameID | current | expected
-- | -- | --
Family Name | Reem Kufi Fun | Reem Kufi Fun
Subfamily Name | Regular | Regular
Full Name | Reem Kufi Fun | Reem Kufi Fun Regular
Poscript Name | ReemKufiFun | ReemKufiFun-Regular

**Comment by khaledhosny** [comment]
> Also, while you're at it, please update the name table to the "expected" values:
> nameID 	current 	expected
> Family Name 	Reem Kufi Fun 	Reem Kufi Fun
> Subfamily Name 	Regular 	Regular
> Full Name 	Reem Kufi Fun 	Reem Kufi Fun Regular
> Poscript Name 	ReemKufiFun 	ReemKufiFun-Regular

This makes no sense, it is a variable font, why there should be “Regular” in the name? I think it is even optional for static fonts.

**Comment by yanone** [comment]
I'll get back to you about this

**Comment by yanone** [comment]
Okay, please ignore the comment about the name.

**Comment by khaledhosny** [comment]
> Please integrate `maximum_color` of the `nanoemoji` package into your build setup to expand the `COLR` table into an `SVG` table and provide us with a new binary.

This is a `COLR` v0 font, are you sure you want an `SVG` table?

**Comment by yanone** [comment]
OMG, you're completely right. We misinterpreted the situation because the respective fontbakery check is just not yet part of the official release used by our automated PR tests and so made a wrong human-level judgement about the SVG table. Forget everything I said. Closing this.
