### ISSUE TITLE
RFN?

### ISSUE THREAD

**Issue by aaronbell** [alif-type/reem-kufi#40]
I note that the OFL file mentions that the font has a Reserved Font Name, but the line says, 'Reserved Font Name "Josefin Sans".' There is no mention of an RFN in the file name table. 

Does the font have an RFN? If so, the OFL.txt file should be updated.

**Comment by khaledhosny** [comment]
The OFL.txt is correct (the RFN is inherited from [Josefin Sans](https://github.com/googlefonts/josefinsans)).

**Comment by aaronbell** [comment]
Ahh, I see. That makes sense. Thanks!
