### ISSUE TITLE
My Cyrillic characters implementation

### ISSUE THREAD

**Issue by Phyan** [alif-type/reem-kufi#41]
I really wanted to thank you for this wonderful font, which I now have as my main system font on my phone. It looks incredible! 🤩
I was a little upset by the fact that such a cool font has no Cyrillic support and some time ago I decided to add Cyrillic character support to it, and here are some of my workings:
![image](https://user-images.githubusercontent.com/66014175/227600657-90808109-dfd1-4eaf-bbc8-7edfec492ab3.png)
![image](https://user-images.githubusercontent.com/66014175/227600730-aa0cecad-ab7c-4fdc-9bea-d601f685c7ac.png)

If you want, I can give you my workings for further polishing, and possibly releasing them as an official. That would be extremely cool!

**Comment by khaledhosny** [comment]
Thanks for your offer, but I didn’t design the Latin part, it is taken from [Josefin Sans](https://github.com/googlefonts/josefinsans), so that would be the proper place to add your Cyrillic. See also https://github.com/googlefonts/josefinsans/issues/24.

**Comment by Phyan** [comment]
Thank you for your reply! I'll try to look into this issue further
