### ISSUE TITLE
make:   /bin/sh: 1: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by felipesanches** [alif-type/reem-kufi#7]
felipe@guarana:~/devel/github_felipesanches/reem-kufi$ make ttf
   GEN  ReemKufi-Regular.ttf
/bin/sh: 1: Syntax error: "(" unexpected
make: **\* [ReemKufi-Regular.ttf] Error 2

**Comment by felipesanches** [comment]
I need to generate these TTF files in order to verify if my changes to the implementation of a fontbakery test works. This font project was mentioned as an example at https://github.com/googlefonts/fontbakery/issues/820

**Comment by khaledhosny** [comment]
You need to use Bash, I have changed the Makefile to make sure this is what make uses.
